// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/luma.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target collection (optional, can be inferred from query)
	Collection string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// The query string (SQL, CQL, or JSON MQL)
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// The dialect/format of the query
	// "sql-pg", "sql-mysql", "cql", "mql", "lumair-json"
	Dialect string `protobuf:"bytes,3,opt,name=dialect,proto3" json:"dialect,omitempty"`
	// Optional binary payload (e.g. serialized LumaIR or params)
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_luma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_luma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_luma_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *QueryRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QueryResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Result data (JSON or binary encoded rows)
	Result []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Metadata
	RowsAffected  int64  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ContentType   string `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "json", "msgpack", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_luma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_luma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_luma_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_proto_luma_proto protoreflect.FileDescriptor

const file_proto_luma_proto_rawDesc = "" +
	"\n" +
	"\x10proto/luma.proto\x12\aluma.v1\"x\n" +
	"\fQueryRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x18\n" +
	"\adialect\x18\x03 \x01(\tR\adialect\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x9f\x01\n" +
	"\rQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12#\n" +
	"\rrows_affected\x18\x04 \x01(\x03R\frowsAffected\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType2\x82\x01\n" +
	"\vLumaService\x128\n" +
	"\aExecute\x12\x15.luma.v1.QueryRequest\x1a\x16.luma.v1.QueryResponse\x129\n" +
	"\x06Stream\x12\x15.luma.v1.QueryRequest\x1a\x16.luma.v1.QueryResponse0\x01B&Z$github.com/lumadb/cluster/pkg/api/pbb\x06proto3"

var (
	file_proto_luma_proto_rawDescOnce sync.Once
	file_proto_luma_proto_rawDescData []byte
)

func file_proto_luma_proto_rawDescGZIP() []byte {
	file_proto_luma_proto_rawDescOnce.Do(func() {
		file_proto_luma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_luma_proto_rawDesc), len(file_proto_luma_proto_rawDesc)))
	})
	return file_proto_luma_proto_rawDescData
}

var file_proto_luma_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_luma_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: luma.v1.QueryRequest
	(*QueryResponse)(nil), // 1: luma.v1.QueryResponse
}
var file_proto_luma_proto_depIdxs = []int32{
	0, // 0: luma.v1.LumaService.Execute:input_type -> luma.v1.QueryRequest
	0, // 1: luma.v1.LumaService.Stream:input_type -> luma.v1.QueryRequest
	1, // 2: luma.v1.LumaService.Execute:output_type -> luma.v1.QueryResponse
	1, // 3: luma.v1.LumaService.Stream:output_type -> luma.v1.QueryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_luma_proto_init() }
func file_proto_luma_proto_init() {
	if File_proto_luma_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_luma_proto_rawDesc), len(file_proto_luma_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_luma_proto_goTypes,
		DependencyIndexes: file_proto_luma_proto_depIdxs,
		MessageInfos:      file_proto_luma_proto_msgTypes,
	}.Build()
	File_proto_luma_proto = out.File
	file_proto_luma_proto_goTypes = nil
	file_proto_luma_proto_depIdxs = nil
}
