// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/luma.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LumaService_Execute_FullMethodName = "/luma.v1.LumaService/Execute"
	LumaService_Stream_FullMethodName  = "/luma.v1.LumaService/Stream"
)

// LumaServiceClient is the client API for LumaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LumaServiceClient interface {
	// Execute a single query (unary)
	Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Stream results (for large result sets)
	Stream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
}

type lumaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLumaServiceClient(cc grpc.ClientConnInterface) LumaServiceClient {
	return &lumaServiceClient{cc}
}

func (c *lumaServiceClient) Execute(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, LumaService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lumaServiceClient) Stream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LumaService_ServiceDesc.Streams[0], LumaService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumaService_StreamClient = grpc.ServerStreamingClient[QueryResponse]

// LumaServiceServer is the server API for LumaService service.
// All implementations must embed UnimplementedLumaServiceServer
// for forward compatibility.
type LumaServiceServer interface {
	// Execute a single query (unary)
	Execute(context.Context, *QueryRequest) (*QueryResponse, error)
	// Stream results (for large result sets)
	Stream(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	mustEmbedUnimplementedLumaServiceServer()
}

// UnimplementedLumaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLumaServiceServer struct{}

func (UnimplementedLumaServiceServer) Execute(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedLumaServiceServer) Stream(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedLumaServiceServer) mustEmbedUnimplementedLumaServiceServer() {}
func (UnimplementedLumaServiceServer) testEmbeddedByValue()                     {}

// UnsafeLumaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LumaServiceServer will
// result in compilation errors.
type UnsafeLumaServiceServer interface {
	mustEmbedUnimplementedLumaServiceServer()
}

func RegisterLumaServiceServer(s grpc.ServiceRegistrar, srv LumaServiceServer) {
	// If the following call panics, it indicates UnimplementedLumaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LumaService_ServiceDesc, srv)
}

func _LumaService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LumaServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LumaService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LumaServiceServer).Execute(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LumaService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LumaServiceServer).Stream(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LumaService_StreamServer = grpc.ServerStreamingServer[QueryResponse]

// LumaService_ServiceDesc is the grpc.ServiceDesc for LumaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LumaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "luma.v1.LumaService",
	HandlerType: (*LumaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _LumaService_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _LumaService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/luma.proto",
}
